### ISSUE TITLE
IndexError: Argument passed to at() was not in the map.

### ISSUE THREAD

**Issue by pratiklikharOLA** [DerryHub/BEVFormer_tensorrt#10]
Getting the following error while converting to onnx:

```
File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 605, in _optimize_graph
    _C._jit_pass_peephole(graph, True)
IndexError: Argument passed to at() was not in the map.
```

**Comment by DerryHub** [comment]
Please provide your environment version. Is your environment consistent with the requirements of README?

**Comment by pratiklikharOLA** [comment]
Hi Derry,

I have everything consistent with the requirements except I have CUDA-11.8 instead of CUDA-11.6.
Also during Unit Test of Custom TensorRT Plugins, I am getting the following errors:

`======================================================================
ERROR: test_fp16 (det2trt.models.utils.test_trt_ops.test_modulated_deformable_conv2d.ModulatedDeformableConv2dTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_modulated_deformable_conv2d.py", line 54, in setUp
    self.buildEngine(opset_version=13)
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/base_test_case.py", line 87, in buildEngine
    engine = pth2trt(
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/utils.py", line 75, in pth2trt
    torch.onnx.export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 605, in _optimize_graph
    _C._jit_pass_peephole(graph, True)
IndexError: Argument passed to at() was not in the map.

======================================================================
ERROR: test_fp32 (det2trt.models.utils.test_trt_ops.test_modulated_deformable_conv2d.ModulatedDeformableConv2dTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_modulated_deformable_conv2d.py", line 54, in setUp
    self.buildEngine(opset_version=13)
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/base_test_case.py", line 95, in buildEngine
    engine = pth2trt(
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/utils.py", line 75, in pth2trt
    torch.onnx.export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 605, in _optimize_graph
    _C._jit_pass_peephole(graph, True)
IndexError: Argument passed to at() was not in the map.

======================================================================
ERROR: test_fp16 (det2trt.models.utils.test_trt_ops.test_modulated_deformable_conv2d.ModulatedDeformableConv2dTestCase2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_modulated_deformable_conv2d.py", line 129, in setUp
    self.buildEngine(opset_version=13)
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/base_test_case.py", line 87, in buildEngine
    engine = pth2trt(
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/utils.py", line 75, in pth2trt
    torch.onnx.export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 605, in _optimize_graph
    _C._jit_pass_peephole(graph, True)
IndexError: Argument passed to at() was not in the map.

======================================================================
ERROR: test_fp32 (det2trt.models.utils.test_trt_ops.test_modulated_deformable_conv2d.ModulatedDeformableConv2dTestCase2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_modulated_deformable_conv2d.py", line 129, in setUp
    self.buildEngine(opset_version=13)
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/base_test_case.py", line 95, in buildEngine
    engine = pth2trt(
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/utils.py", line 75, in pth2trt
    torch.onnx.export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 605, in _optimize_graph
    _C._jit_pass_peephole(graph, True)
IndexError: Argument passed to at() was not in the map.

======================================================================
FAIL: test_fp16_bilinear (det2trt.models.utils.test_trt_ops.test_rotate.RotateTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_rotate.py", line 91, in test_fp16_bilinear
    self.fp16_case(0.01)
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_rotate.py", line 82, in fp16_case
    self.assertLessEqual(cost, delta)
AssertionError: 0.1892 not less than or equal to 0.01

======================================================================
FAIL: test_fp16_nearest (det2trt.models.utils.test_trt_ops.test_rotate.RotateTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_rotate.py", line 94, in test_fp16_nearest
    self.fp16_case(0.02)
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_rotate.py", line 82, in fp16_case
    self.assertLessEqual(cost, delta)
AssertionError: 0.2388 not less than or equal to 0.02

======================================================================
FAIL: test_fp32_bilinear (det2trt.models.utils.test_trt_ops.test_rotate.RotateTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_rotate.py", line 85, in test_fp32_bilinear
    self.fp32_case(0.01)
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_rotate.py", line 74, in fp32_case
    self.assertLessEqual(cost, delta)
AssertionError: 0.15744261 not less than or equal to 0.01

======================================================================
FAIL: test_fp16_bilinear (det2trt.models.utils.test_trt_ops.test_rotate.RotateTestCase2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_rotate.py", line 176, in test_fp16_bilinear
    self.fp16_case(0.01)
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_rotate.py", line 167, in fp16_case
    self.assertLessEqual(cost, delta)
AssertionError: 0.1893 not less than or equal to 0.01

======================================================================
FAIL: test_fp16_nearest (det2trt.models.utils.test_trt_ops.test_rotate.RotateTestCase2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_rotate.py", line 179, in test_fp16_nearest
    self.fp16_case(0.02)
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_rotate.py", line 167, in fp16_case
    self.assertLessEqual(cost, delta)
AssertionError: 0.2389 not less than or equal to 0.02

======================================================================
FAIL: test_fp32_bilinear (det2trt.models.utils.test_trt_ops.test_rotate.RotateTestCase2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_rotate.py", line 170, in test_fp32_bilinear
    self.fp32_case(0.01)
  File "/workspace/pratik/BEVFormer_tensorrt/./det2trt/models/utils/test_trt_ops/test_rotate.py", line 159, in fp32_case
    self.assertLessEqual(cost, delta)
AssertionError: 0.15744261 not less than or equal to 0.01

----------------------------------------------------------------------
Ran 136 tests in 437.515s

FAILED (failures=6, errors=4)`

I think the error comes from ModulatedDeformableConv2d.

**Comment by DerryHub** [comment]
I've had similar errors before with PyTorch 1.13.1. Please check your PyTorch vision. Only version 1.12.1 is supported.

**Comment by pratiklikharOLA** [comment]
Thanks Derry! It worked. BTW any idea why this is not working with PyTorch 1.13.x or above?

**Comment by DerryHub** [comment]
Glad to hear that! I'm confused, too. I guess this is probably because some interface of pth2onnx changes in pytorch1.13.x.

**Comment by pratiklikharOLA** [comment]
Thanks a lot!
