### ISSUE TITLE
sh sample/test_trt_ops.sh error

### ISSUE THREAD

**Issue by zouzouwei** [DerryHub/BEVFormer_tensorrt#16]
I followed the steps,until 
![image](https://user-images.githubusercontent.com/15826704/215927073-8c7f71db-7149-4354-9e1f-16f2121b8a4c.png)
a lot of error appeared.
![image](https://user-images.githubusercontent.com/15826704/215926698-cdd3d623-91e7-4045-9305-82ff5dd0a267.png)

I try to skip this step and make the next step
![image](https://user-images.githubusercontent.com/15826704/215927288-c6be2076-3f24-4dbb-8b6e-239ed05d505f.png)
There it is，Tensors of type TensorImpl do not have sizes。
`
sh samples/bevformer/base/pth_evaluate.sh -d 0
Running on the GPU: 0
Loaded tensorrt plugins from /home/ying/data/code/BEVFormer_tensorrt/TensorRT/lib/libtensorrt_ops.so
load checkpoint from local path: checkpoints/pytorch/bevformer_r101_dcn_24ep.pth
2023-02-01 10:06:11,641 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.0.conv2 is upgraded to version 2.
WARNING: Logging before flag parsing goes to stderr.
I0201 10:06:11.641491 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.0.conv2 is upgraded to version 2.
2023-02-01 10:06:11,644 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.1.conv2 is upgraded to version 2.
I0201 10:06:11.644044 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.1.conv2 is upgraded to version 2.
2023-02-01 10:06:11,645 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.2.conv2 is upgraded to version 2.
I0201 10:06:11.645901 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.2.conv2 is upgraded to version 2.
2023-02-01 10:06:11,647 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.3.conv2 is upgraded to version 2.
I0201 10:06:11.647749 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.3.conv2 is upgraded to version 2.
2023-02-01 10:06:11,649 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.4.conv2 is upgraded to version 2.
I0201 10:06:11.649613 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.4.conv2 is upgraded to version 2.
2023-02-01 10:06:11,651 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.5.conv2 is upgraded to version 2.
I0201 10:06:11.651456 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.5.conv2 is upgraded to version 2.
2023-02-01 10:06:11,653 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.6.conv2 is upgraded to version 2.
I0201 10:06:11.653303 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.6.conv2 is upgraded to version 2.
2023-02-01 10:06:11,655 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.7.conv2 is upgraded to version 2.
I0201 10:06:11.655148 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.7.conv2 is upgraded to version 2.
2023-02-01 10:06:11,656 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.8.conv2 is upgraded to version 2.
I0201 10:06:11.656990 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.8.conv2 is upgraded to version 2.
2023-02-01 10:06:11,658 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.9.conv2 is upgraded to version 2.
I0201 10:06:11.658817 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.9.conv2 is upgraded to version 2.
2023-02-01 10:06:11,660 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.10.conv2 is upgraded to version 2.
I0201 10:06:11.660640 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.10.conv2 is upgraded to version 2.
2023-02-01 10:06:11,662 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.11.conv2 is upgraded to version 2.
I0201 10:06:11.662476 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.11.conv2 is upgraded to version 2.
2023-02-01 10:06:11,664 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.12.conv2 is upgraded to version 2.
I0201 10:06:11.664302 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.12.conv2 is upgraded to version 2.
2023-02-01 10:06:11,666 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.13.conv2 is upgraded to version 2.
I0201 10:06:11.666151 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.13.conv2 is upgraded to version 2.
2023-02-01 10:06:11,668 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.14.conv2 is upgraded to version 2.
I0201 10:06:11.668013 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.14.conv2 is upgraded to version 2.
2023-02-01 10:06:11,669 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.15.conv2 is upgraded to version 2.
I0201 10:06:11.669847 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.15.conv2 is upgraded to version 2.
2023-02-01 10:06:11,671 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.16.conv2 is upgraded to version 2.
I0201 10:06:11.671697 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.16.conv2 is upgraded to version 2.
2023-02-01 10:06:11,673 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.17.conv2 is upgraded to version 2.
I0201 10:06:11.673552 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.17.conv2 is upgraded to version 2.
2023-02-01 10:06:11,675 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.18.conv2 is upgraded to version 2.
I0201 10:06:11.675375 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.18.conv2 is upgraded to version 2.
2023-02-01 10:06:11,677 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.19.conv2 is upgraded to version 2.
I0201 10:06:11.677223 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.19.conv2 is upgraded to version 2.
2023-02-01 10:06:11,679 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.20.conv2 is upgraded to version 2.
I0201 10:06:11.679056 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.20.conv2 is upgraded to version 2.
2023-02-01 10:06:11,680 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.21.conv2 is upgraded to version 2.
I0201 10:06:11.680887 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.21.conv2 is upgraded to version 2.
2023-02-01 10:06:11,682 - root - INFO - ModulatedDeformConvPack img_backbone.layer3.22.conv2 is upgraded to version 2.
I0201 10:06:11.682716 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer3.22.conv2 is upgraded to version 2.
2023-02-01 10:06:11,684 - root - INFO - ModulatedDeformConvPack img_backbone.layer4.0.conv2 is upgraded to version 2.
I0201 10:06:11.684802 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer4.0.conv2 is upgraded to version 2.
2023-02-01 10:06:11,689 - root - INFO - ModulatedDeformConvPack img_backbone.layer4.1.conv2 is upgraded to version 2.
I0201 10:06:11.689321 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer4.1.conv2 is upgraded to version 2.
2023-02-01 10:06:11,692 - root - INFO - ModulatedDeformConvPack img_backbone.layer4.2.conv2 is upgraded to version 2.
I0201 10:06:11.692627 140030840562880 logging.py:107] ModulatedDeformConvPack img_backbone.layer4.2.conv2 is upgraded to version 2.
WARNING!!!!, Only can be used for obtain inference speed!!!!
[                                                  ] 0/162, elapsed: 0s, ETA:/home/ying/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "tools/bevformer/evaluate_pth.py", line 138, in <module>
    main()
  File "tools/bevformer/evaluate_pth.py", line 103, in main
    bev_embed, outputs_classes, outputs_coords = model(
  File "/home/ying/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ying/data/code/BEVFormer_tensorrt/mmcv/mmcv/parallel/data_parallel.py", line 50, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/ying/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ying/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ying/data/code/BEVFormer_tensorrt/./det2trt/models/detector/bevformer.py", line 41, in forward_trt
    bev_embed, outputs_classes, outputs_coords = self.pts_bbox_head.forward_trt(
  File "/home/ying/data/code/BEVFormer_tensorrt/./det2trt/models/dense_heads/bevformer_head.py", line 134, in forward_trt
    outputs = self.transformer.forward_trt(
  File "/home/ying/data/code/BEVFormer_tensorrt/./det2trt/models/modules/transformer.py", line 196, in forward_trt
    bev_embed = self.get_bev_features_trt(
  File "/home/ying/data/code/BEVFormer_tensorrt/./det2trt/models/modules/transformer.py", line 160, in get_bev_features_trt
    bev_embed = self.encoder.forward_trt(
  File "/home/ying/data/code/BEVFormer_tensorrt/./det2trt/models/modules/encoder.py", line 136, in forward_trt
    output = layer.forward_trt(
  File "/home/ying/data/code/BEVFormer_tensorrt/./det2trt/models/modules/encoder.py", line 454, in forward_trt
    query = self.attentions[attn_index].forward_trt(
  File "/home/ying/data/code/BEVFormer_tensorrt/./det2trt/models/modules/temporal_self_attention.py", line 274, in forward_trt
    output = MultiScaleDeformableAttnFunction.apply(
  File "/home/ying/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 118, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/ying/data/code/BEVFormer_tensorrt/./third_party/bevformer/models/modules/multi_scale_deformable_attn_function.py", line 142, in forward
    output = ext_module.ms_deform_attn_forward(
RuntimeError: Tensors of type TensorImpl do not have 

> sizes`
![image](https://user-images.githubusercontent.com/15826704/215927609-6900a714-34c2-43aa-83c6-40e08d40e9c6.png)

**Comment by zouzouwei** [comment]
> For the ERROR in `samples/test_trt_ops.sh`, you can change the line
> 
> https://github.com/DerryHub/BEVFormer_tensorrt/blob/77c7f554a145719eda1502a69bc6736071f4c77d/det2trt/models/utils/test_trt_ops/utils.py#L12
> 
> to `TRT_LOGGER = trt.Logger(trt.Logger.VERBOSE)` to see how the error happens.
> For `RuntimeError: Tensors of type TensorImpl do not have sizes`, I've never encountered such error. Please check the versions of PyTorch and MMCV.

hi，I wonder if this is related to the Tensorrt version.

my tensorrt 8.4.0.6，torch 1.12+cu113

mmcv 、 mmdet 、mmdeploy both git clone Local installation

thank for you

**Comment by DerryHub** [comment]
`pth_evaluate.sh` doesn't depend on tensorrt.
