### ISSUE TITLE
No module named 'pytorch_quantization

### ISSUE THREAD

**Issue by Isaac-xie** [DerryHub/BEVFormer_tensorrt#61]
when I try to use"sh samples/test_trt_ops.sh",I meet the error"No module named 'pytorch_quantization",did I missed some steps?

here is log 
`Running on the GPU: 0
Traceback (most recent call last):
  File "tools/test_trt_ops.py", line 6, in <module>
    import det2trt
  File "/media/13data2/xzz/code/tensorRT/BEVFormer_tensorrt/./det2trt/__init__.py", line 1, in <module>
    from .models import *
  File "/media/13data2/xzz/code/tensorRT/BEVFormer_tensorrt/./det2trt/models/__init__.py", line 1, in <module>
    from .backbones import *
  File "/media/13data2/xzz/code/tensorRT/BEVFormer_tensorrt/./det2trt/models/backbones/__init__.py", line 1, in <module>
    from .csp_darknet import CSPDarknetQ
  File "/media/13data2/xzz/code/tensorRT/BEVFormer_tensorrt/./det2trt/models/backbones/csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "/media/13data2/xzz/code/tensorRT/BEVFormer_tensorrt/./det2trt/models/utils/__init__.py", line 1, in <module>
    from .scp_layer import CSPLayer
  File "/media/13data2/xzz/code/tensorRT/BEVFormer_tensorrt/./det2trt/models/utils/scp_layer.py", line 6, in <module>
    from pytorch_quantization import nn as quant_nn
ModuleNotFoundError: No module named 'pytorch_quantization'
`

**Comment by DerryHub** [comment]
Please install it following https://github.com/NVIDIA/TensorRT/tree/release/8.6/tools/pytorch-quantization
